name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 service1/app.py service2/app.py

      - name: Run tests
        run: |
          pip install pytest
          pytest service1/test_app.py
          pytest service2/test_app.py

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push service1 image
        uses: docker/build-push-action@v5
        with:
          context: ./service1
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/service1:latest

      - name: Build and push service2 image
        uses: docker/build-push-action@v5
        with:
          context: ./service2
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/service2:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to Kubernetes
        run: |
          echo "Add your kubectl apply commands here for cloud deployment."
